name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        rustup target add thumbv6m-none-eabi
        cargo build --verbose 
    - name: fmt
      run: |
        rustup component add rustfmt
        cargo fmt -- --check -l
    - name: clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
