name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        rustup target add thumbv6m-none-eabi
        cargo build --verbose 
    - name: fmt
      run: |
        rustup component add rustfmt
        cargo fmt -- --check -l
    - name: clippy
      run: |
        rustup component add clippy
        cargo clippy --no-deps -- -D warnings
    - name: tests
      run: 'cargo test --verbose --package smallball --target $(rustc -vV | sed -n "s|host: ||p")' 

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
      - run: 'cargo tarpaulin --packages smallball --target $(rustc -vV | sed -n "s|host: ||p") --ignore-tests --fail-under 100'
